# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
- stage: Build
  displayName: Build stage
  jobs:
    - deployment: deploy
      displayName: Load Testing
      pool:
        vmImage: ubuntu-latest
      environment: loadtesting
      strategy:
        runOnce:
          deploy:
            steps:
              - task: AzureLoadTest@1
                displayName: Load Testing
                inputs:
                  azureSubscription: ALT_SC_73bfea0e-9306-4531-9c32-52dcc2f5401d
                  loadTestConfigFile: '/home/vsts/work/1/s/logintest.yaml'
                  loadTestResource: MiguelGarcia
                  resourceGroup: MiguelGarcia
              - publish: $(System.DefaultWorkingDirectory)/loadTest
                artifact: loadTestResults