# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
- stage: Build
  displayName: Build stage
  jobs:
    - deployment: deploy
      displayName: Load Testing
      pool:
        vmImage: ubuntu-latest
      environment: loadtesting
      strategy:
        runOnce:
          deploy:
            steps:
              - task: AzureLoadTest@1
                displayName: Load Testing
                inputs:
                  azureSubscription: dbb44df0-8a01-4b7a-84c7-a15173ede004
                  loadTestConfigFile: logintest.yaml
                  loadTestResource: MiguelGarcia
                  resourceGroup: MiguelGarcia
              - publish: $(System.DefaultWorkingDirectory)/loadTest
                artifact: loadTestResults